// Generated by CoffeeScript 1.7.1
var make_year, months;

window.database = {};
window.timeline_db = [];


MONTH_NAMES = {
    1: "January",
    2: "Febuary",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
};

$.extend(Trove.defaults, {
    q: "(" + town + ") -title:(Advertising)",
    include: "articletext,links,years",
    zone: "newspaper,picture"
});
Trove.page_size = 50;

function load_data_to_dom(data, ignore_scroll) {
    if ($("#timeline").children().length === 0) {
        // Nothing in timeline. Just ignore the scrolling stuff.
        ignore_scroll = true;
    } else if ($(window).scrollTop() < NAVBAR_HEIGHT) {
        // The window is near the top. Let's keep it there.
        ignore_scroll = 1 + $(window).scrollTop(); // Truthy
    }

    if (!ignore_scroll) {
        // Select all `date-container`s that are on the screen.
        var $w = $(window);
        var $aDateShown = $(".date-container:onScreen");
        var deltaOffset = $w.scrollTop() - $aDateShown.offset().top;
        console.log("Old Scroll: ", $w.scrollTop());
    }

    var id = "trove-content-id-" + data.id;

    var c = $("#" + id);
    if (c.length === 0) {
        var c = $(data.to_html_preview(data));
        c.attr("id", id);
    }

    var content = get_date_for(data.year, data.month, data.day);

    var left = content.find(".left-content");
    var right = content.find(".right-content");

    var ll = height_of_children(left);
    var rl = height_of_children(right);

    if (rl < ll) {
        right.append(c);
    } else {
        left.append(c);
    }
    if (!ignore_scroll) {
        var scroll = $w.scrollTop();
        $w.scrollTop(deltaOffset + $aDateShown.offset().top);
        if(scroll != $w.scrollTop()) {
            console.log("New Scroll: ", $w.scrollTop());
        }
    } else if (ignore_scroll !== true) {
        // ignore scroll is a number(probably).
        $(window).scrollTop(ignore_scroll - 1); // Decode it.
    }

    // Now update the headings at the top.

    $myNav = $("#navbar-month-" + data.month);
    $myNav.removeClass("navbar-month-missing");
}

function init_navbar_months(current_year) {
    function update_current_month() {
        var $m = $(".month-container:onScreen").first();
        var month = $m.attr("month");
        $(".navbar-month-current").removeClass("navbar-month-current");
        $("#navbar-month-" + month).addClass("navbar-month-current");
    }
    $(window).scroll(update_current_month);
    update_current_month();

    navbar_month_click_handler = function(event) {
        var y = "#y" + current_year;
        var month = event.data;
        var $m = $(y + "m" + month);
        var $w = $(window);
        if($m.length !== 0) {
            $w.scrollTop($m.offset().top - NAVBAR_HEIGHT);
        } else {
            // Search down then search up.
            for(var m = month + 1; m <= 12; m++) {
                $m = $(y + "m" + m);
                if($m.length !== 0) {
                    $w.scrollTop($m.offset().top - NAVBAR_HEIGHT);
                    return;
                }
            }
            for(var m = month - 1; m >= 1; m--) {
                $m = $(y + "m" + m);
                if($m.length !== 0) {
                    $w.scrollTop($m.offset().top - NAVBAR_HEIGHT);
                    return;
                }
            }
            // Oh, we don't have any months - sigh.
            // We'll just scroll to the top of the page.
            $w.scrollTop(0);
        }
    }
    $("#navbar-month-container").empty();
    for(var month = 1; month <= 12; month++) {
        var c = $("<a></a>").addClass("navbar-month navbar-month-missing");
        c.text(MONTH_NAMES[month].substring(0,3));
        c.attr("id", "navbar-month-" + month);
        c.click(month, navbar_month_click_handler);

        $("#navbar-month-container").append(c);
    }
}


$(window).ready(function () {
    $(document).ajaxStart(function () {
        $("#loading-spinner").removeClass("hidden");
    });
    $(document).ajaxStop(function () {
        $("#loading-spinner").addClass("hidden");
    });

    window.NAVBAR_HEIGHT = $(".navbar").first().height()

    // Below is for year init.

    var current_year = 1950;
    window.current_loader = TroveDB.trove_loaders.get(current_year);
    window.current_loader.execute();

    init_navbar_months(current_year);

    TroveDB.database.add_data_listener(function (data, year, id) {
        if (year !== current_year) {
            return; // Discard event as its data will not be shown.
        }
        load_data_to_dom(data);
    });
});
