// Generated by CoffeeScript 1.7.1
var __slice = [].slice;

Trove = {};

Trove.defaults = {};

Trove.cache = {};

Trove.page_size = 20;

Trove.listing = function(page, callback) {
    var q, _ref;
    if (!$.isNumeric(page)) {
        _ref = [page, 0], callback = _ref[0], page = _ref[1];
    }
    q = {
        s: page * Trove.page_size,
        n: Trove.page_size
    };
    q = $.extend(q, Trove.defaults);
    return Trove.api_call(q, callback);
};

Trove.api_call = function() {
    var callbacks, data;
    data = arguments[0], callbacks = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return $.ajax({
        url: "api.php",
        data: data,
        complete: callbacks
    });
};

Trove.date_listing = function(start_year, end_year, page, callback) {
    if (!$.isNumeric(page)) {
        callback = page;
        page = 0;
    }
    var q = {
        s: page * Trove.page_size,
        n: Trove.page_size
    };
    q = $.extend(q, Trove.defaults);
    if (!start_year) {
        start_year = "1000";
        q["sortby"] = "datedesc";
    }
    if (!end_year) {
        end_year = "3000";
        q["sortby"] = "dateasc";
    }
    q["q"] = "(" + q["q"] + ")  date:[" + start_year + " TO " + end_year + "]";
    return Trove.api_call(q, callback);
};
