// Generated by CoffeeScript 1.7.1
var __slice = [].slice;

this.Trove = (function() {
  function Trove() {}

  Trove.prototype.defaults = {};

  Trove.prototype.cache = {};

  Trove.prototype.page_size = 20;

  Trove.prototype.listing = function(page, callback) {
    var q, _ref;
    if (!$.isNumeric(page)) {
      _ref = [page, 0], callback = _ref[0], page = _ref[1];
    }
    q = {
      s: page * this.page_size,
      n: this.page_size
    };
    q = $.extend(q, this.defaults);
    return this.api_call(q, callback);
  };

  Trove.prototype.api_call = function() {
    var callbacks, data;
    data = arguments[0], callbacks = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return $.ajax({
      url: "api.php",
      data: data,
      complete: callbacks
    });
  };

  Trove.prototype.date_listing = function(start_year, end_year, page, callback) {
    var q, _ref;
    if (!$.isNumeric(page)) {
      _ref = [page, 0], callback = _ref[0], page = _ref[1];
    }
    q = {
      s: page * this.page_size,
      n: this.page_size
    };
    q = $.extend(q, this.defaults);
    if (!start_year) {
      start_year = "1";
      q["sortby"] = "datedesc";
    }
    if (!end_year) {
      end_year = "3000";
      q["sortby"] = "dateasc";
    }
    q["q"] = "(" + q['q'] + ")  date:[" + start_year + " TO " + end_year + "]";
    return this.api_call(q, callback);
  };

  return Trove;

})();
